package brf.peru.view;

import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;

public class ViewEscolhaAbateP extends javax.swing.JFrame {

    /**
     * Creates new form ViewEscolhaAbateP
     */
    public ViewEscolhaAbateP() {
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        abate1Label = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        opcaoJFT = new javax.swing.JFormattedTextField();
        abate2Label = new javax.swing.JLabel();
        abate3Label = new javax.swing.JLabel();
        qtdeAbate1Label = new javax.swing.JLabel();
        qtdeAbate2Label = new javax.swing.JLabel();
        qtdeAbate3Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel37.setText("Selecione qual abate digitar:");

        abate1Label.setText("[1] - Primeiro Abate");

        jLabel39.setText("[9] - Voltar");

        jLabel40.setText("[0] - Sair");

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("Opção");

        try {
            opcaoJFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        opcaoJFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        abate2Label.setText("[2] - Segundo Abate");

        abate3Label.setText("[3] - Terceiro Abate");

        qtdeAbate1Label.setForeground(new java.awt.Color(0, 153, 255));
        qtdeAbate1Label.setText("0 registro(s)");

        qtdeAbate2Label.setForeground(new java.awt.Color(0, 153, 255));
        qtdeAbate2Label.setText("0 registro(s)");

        qtdeAbate3Label.setForeground(new java.awt.Color(0, 153, 255));
        qtdeAbate3Label.setText("0 registro(s)");
        
        abate4Label = new JLabel();
        abate4Label.setText("[4] - Quarto Abate");
        
        qtdeAbate4Label = new JLabel();
        qtdeAbate4Label.setText("0 registro(s)");
        qtdeAbate4Label.setForeground(new Color(0, 153, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11Layout.setHorizontalGroup(
        	jPanel11Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel11Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel11Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel37, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        				.addGroup(jPanel11Layout.createSequentialGroup()
        					.addGroup(jPanel11Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(abate1Label, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(abate2Label, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(abate3Label, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addPreferredGap(ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
        					.addGroup(jPanel11Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(qtdeAbate2Label, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        						.addComponent(qtdeAbate1Label, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(qtdeAbate3Label, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        				.addGroup(jPanel11Layout.createSequentialGroup()
        					.addComponent(abate4Label, GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(qtdeAbate4Label, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel11Layout.createSequentialGroup()
        					.addComponent(jLabel41, GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        					.addGap(10)
        					.addComponent(opcaoJFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jLabel40, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        				.addComponent(jLabel39, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
        	jPanel11Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel11Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel37)
        			.addGap(18)
        			.addGroup(jPanel11Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(abate1Label)
        				.addComponent(qtdeAbate1Label))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel11Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(abate2Label)
        				.addComponent(qtdeAbate2Label))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel11Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(abate3Label)
        				.addComponent(qtdeAbate3Label))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel11Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(abate4Label)
        				.addComponent(qtdeAbate4Label))
        			.addGap(28)
        			.addComponent(jLabel39)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel40)
        			.addGap(18)
        			.addGroup(jPanel11Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(opcaoJFT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel41))
        			.addContainerGap())
        );
        jPanel11.setLayout(jPanel11Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel11, GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEscolhaAbateP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEscolhaAbateP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEscolhaAbateP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEscolhaAbateP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEscolhaAbateP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abate1Label;
    private javax.swing.JLabel abate2Label;
    private javax.swing.JLabel abate3Label;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JFormattedTextField opcaoJFT;
    private javax.swing.JLabel qtdeAbate1Label;
    private javax.swing.JLabel qtdeAbate2Label;
    private javax.swing.JLabel qtdeAbate3Label;
    private JLabel abate4Label;
    private JLabel qtdeAbate4Label;
	public javax.swing.JLabel getAbate1Label() {
		return abate1Label;
	}



	public void setAbate1Label(javax.swing.JLabel abate1Label) {
		this.abate1Label = abate1Label;
	}



	public javax.swing.JLabel getAbate2Label() {
		return abate2Label;
	}



	public void setAbate2Label(javax.swing.JLabel abate2Label) {
		this.abate2Label = abate2Label;
	}



	public javax.swing.JLabel getAbate3Label() {
		return abate3Label;
	}



	public void setAbate3Label(javax.swing.JLabel abate3Label) {
		this.abate3Label = abate3Label;
	}



	public javax.swing.JLabel getjLabel37() {
		return jLabel37;
	}



	public void setjLabel37(javax.swing.JLabel jLabel37) {
		this.jLabel37 = jLabel37;
	}



	public javax.swing.JLabel getjLabel39() {
		return jLabel39;
	}



	public void setjLabel39(javax.swing.JLabel jLabel39) {
		this.jLabel39 = jLabel39;
	}



	public javax.swing.JLabel getjLabel40() {
		return jLabel40;
	}



	public void setjLabel40(javax.swing.JLabel jLabel40) {
		this.jLabel40 = jLabel40;
	}



	public javax.swing.JLabel getjLabel41() {
		return jLabel41;
	}



	public void setjLabel41(javax.swing.JLabel jLabel41) {
		this.jLabel41 = jLabel41;
	}



	public javax.swing.JPanel getjPanel11() {
		return jPanel11;
	}



	public void setjPanel11(javax.swing.JPanel jPanel11) {
		this.jPanel11 = jPanel11;
	}



	public javax.swing.JFormattedTextField getOpcaoJFT() {
		return opcaoJFT;
	}



	public void setOpcaoJFT(javax.swing.JFormattedTextField opcaoJFT) {
		this.opcaoJFT = opcaoJFT;
	}



	public javax.swing.JLabel getQtdeAbate1Label() {
		return qtdeAbate1Label;
	}



	public void setQtdeAbate1Label(javax.swing.JLabel qtdeAbate1Label) {
		this.qtdeAbate1Label = qtdeAbate1Label;
	}



	public javax.swing.JLabel getQtdeAbate2Label() {
		return qtdeAbate2Label;
	}



	public void setQtdeAbate2Label(javax.swing.JLabel qtdeAbate2Label) {
		this.qtdeAbate2Label = qtdeAbate2Label;
	}



	public javax.swing.JLabel getQtdeAbate3Label() {
		return qtdeAbate3Label;
	}



	public void setQtdeAbate3Label(javax.swing.JLabel qtdeAbate3Label) {
		this.qtdeAbate3Label = qtdeAbate3Label;
	}



	public JLabel getAbate4Label() {
		return abate4Label;
	}



	public void setAbate4Label(JLabel abate4Label) {
		this.abate4Label = abate4Label;
	}



	public JLabel getQtdeAbate4Label() {
		return qtdeAbate4Label;
	}



	public void setQtdeAbate4Label(JLabel qtdeAbate4Label) {
		this.qtdeAbate4Label = qtdeAbate4Label;
	}
}
