package brf.suino.view;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

public class ViewConsumoTST extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	

    /**
     * Creates new form ViewImportarBalanca
     */
    public ViewConsumoTST() {
        initComponents();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        baiaJP = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        dataJFT = new javax.swing.JFormattedTextField();
        tratosJFT = new javax.swing.JFormattedTextField();
        tratosJFT.setEnabled(false);
        jLabel77 = new javax.swing.JLabel();
        registrosLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        opcaoJFT = new javax.swing.JFormattedTextField();
        jLabel78 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ordemHist1 = new javax.swing.JLabel();
        ordemHist2 = new javax.swing.JLabel();
        ordemHist3 = new javax.swing.JLabel();
        ordemHist4 = new javax.swing.JLabel();
        ordemHist5 = new javax.swing.JLabel();
        ordemHist10 = new javax.swing.JLabel();
        ordemHist9 = new javax.swing.JLabel();
        ordemHist8 = new javax.swing.JLabel();
        ordemHist7 = new javax.swing.JLabel();
        ordemHist6 = new javax.swing.JLabel();
        baiaHist7 = new javax.swing.JLabel();
        baiaHist6 = new javax.swing.JLabel();
        baiaHist9 = new javax.swing.JLabel();
        baiaHist10 = new javax.swing.JLabel();
        baiaHist8 = new javax.swing.JLabel();
        baiaHist5 = new javax.swing.JLabel();
        baiaHist4 = new javax.swing.JLabel();
        baiaHist3 = new javax.swing.JLabel();
        baiaHist2 = new javax.swing.JLabel();
        baiaHist1 = new javax.swing.JLabel();
        consumoHist7 = new javax.swing.JLabel();
        consumoHist6 = new javax.swing.JLabel();
        consumoHist9 = new javax.swing.JLabel();
        consumoHist10 = new javax.swing.JLabel();
        consumoHist8 = new javax.swing.JLabel();
        consumoHist5 = new javax.swing.JLabel();
        consumoHist4 = new javax.swing.JLabel();
        consumoHist3 = new javax.swing.JLabel();
        consumoHist2 = new javax.swing.JLabel();
        consumoHist1 = new javax.swing.JLabel();
        pnlConsT = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        baiaJFT1 = new javax.swing.JFormattedTextField();
        baiaJFT1.setEnabled(false);
        baiaJFT2 = new javax.swing.JFormattedTextField();
        baiaJFT2.setEnabled(false);
        baiaJFT3 = new javax.swing.JFormattedTextField();
        baiaJFT3.setEnabled(false);
        baiaJFT4 = new javax.swing.JFormattedTextField();
        baiaJFT4.setEnabled(false);
        baiaJFT5 = new javax.swing.JFormattedTextField();
        baiaJFT5.setEnabled(false);
        baiaJFT6 = new javax.swing.JFormattedTextField();
        baiaJFT6.setEnabled(false);
        baiaJFT7 = new javax.swing.JFormattedTextField();
        baiaJFT7.setEnabled(false);
        baiaJFT8 = new javax.swing.JFormattedTextField();
        baiaJFT8.setEnabled(false);
        baiaJFT9 = new javax.swing.JFormattedTextField();
        baiaJFT9.setEnabled(false);
        baiaJFT10 = new javax.swing.JFormattedTextField();
        baiaJFT10.setEnabled(false);
        consumoJFT1 = new javax.swing.JFormattedTextField();
        consumoJFT1.setEnabled(false);
        consumoJFT2 = new javax.swing.JFormattedTextField();
        consumoJFT2.setEnabled(false);
        consumoJFT3 = new javax.swing.JFormattedTextField();
        consumoJFT3.setEnabled(false);
        consumoJFT4 = new javax.swing.JFormattedTextField();
        consumoJFT4.setEnabled(false);
        consumoJFT5 = new javax.swing.JFormattedTextField();
        consumoJFT5.setEnabled(false);
        consumoJFT6 = new javax.swing.JFormattedTextField();
        consumoJFT6.setEnabled(false);
        consumoJFT7 = new javax.swing.JFormattedTextField();
        consumoJFT7.setEnabled(false);
        consumoJFT8 = new javax.swing.JFormattedTextField();
        consumoJFT8.setEnabled(false);
        consumoJFT9 = new javax.swing.JFormattedTextField();
        consumoJFT9.setEnabled(false);
        consumoJFT10 = new javax.swing.JFormattedTextField();
        consumoJFT10.setEnabled(false);
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        controleJFT = new javax.swing.JFormattedTextField();
        controleJFT.setEnabled(false);
        ordemJFT1 = new javax.swing.JLabel();
        ordemJFT7 = new javax.swing.JLabel();
        ordemJFT2 = new javax.swing.JLabel();
        ordemJFT8 = new javax.swing.JLabel();
        ordemJFT5 = new javax.swing.JLabel();
        ordemJFT9 = new javax.swing.JLabel();
        ordemJFT6 = new javax.swing.JLabel();
        ordemJFT4 = new javax.swing.JLabel();
        ordemJFT3 = new javax.swing.JLabel();
        ordemJFT10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        baiaJP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel44.setText("Data");
        try {
            dataJFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataJFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            tratosJFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tratosJFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel77.setText("Tratos");

        javax.swing.GroupLayout baiaJPLayout = new javax.swing.GroupLayout(baiaJP);
        baiaJPLayout.setHorizontalGroup(
        	baiaJPLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(baiaJPLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel44)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(dataJFT, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel77, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(tratosJFT, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(260, Short.MAX_VALUE))
        );
        baiaJPLayout.setVerticalGroup(
        	baiaJPLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(baiaJPLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(baiaJPLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(baiaJPLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel77)
        					.addComponent(tratosJFT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(baiaJPLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel44)
        					.addComponent(dataJFT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        baiaJP.setLayout(baiaJPLayout);

        registrosLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registrosLabel.setForeground(new java.awt.Color(0, 153, 255));
        registrosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrosLabel.setText("Registros salvos com sucesso!!");

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Escolha uma opção:");

        jLabel25.setText("[1] - Próxima data");

        jLabel50.setText("[0] - Sair");

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel51.setText("Opção");

        try {
            opcaoJFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        opcaoJFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        opcaoJFT.setEnabled(false);

        jLabel78.setText("ESC - Voltar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opcaoJFT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel78, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addGap(21, 21, 21)
                .addComponent(jLabel78)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(opcaoJFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Digitados");

        ordemHist1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemHist2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemHist3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemHist4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemHist5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemHist10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemHist9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemHist8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemHist7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemHist6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        baiaHist7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        baiaHist6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        baiaHist9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        baiaHist10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        baiaHist8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        baiaHist5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        baiaHist4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        baiaHist3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        baiaHist2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        baiaHist1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        consumoHist7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        consumoHist6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        consumoHist9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        consumoHist10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        consumoHist8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        consumoHist5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        consumoHist4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        consumoHist3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        consumoHist2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        consumoHist1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ordemHist1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordemHist2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordemHist3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordemHist4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordemHist5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordemHist6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordemHist7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordemHist8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordemHist9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordemHist10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baiaHist1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baiaHist2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baiaHist3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baiaHist4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baiaHist5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baiaHist6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baiaHist7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baiaHist8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baiaHist9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baiaHist10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consumoHist2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(consumoHist3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consumoHist4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consumoHist5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consumoHist6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consumoHist7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consumoHist8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consumoHist9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consumoHist10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consumoHist1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ordemHist1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordemHist2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordemHist3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordemHist4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordemHist5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordemHist6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordemHist7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordemHist8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordemHist9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordemHist10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(baiaHist1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baiaHist2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baiaHist3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baiaHist4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baiaHist5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baiaHist6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baiaHist7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baiaHist8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baiaHist9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baiaHist10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(consumoHist1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumoHist2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumoHist3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumoHist4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumoHist5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumoHist6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumoHist7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumoHist8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumoHist9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumoHist10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlConsT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ordem");
        try {
            baiaJFT1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        baiaJFT1.setHorizontalAlignment(javax.swing.JTextField.CENTER);


        try {
            baiaJFT2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        baiaJFT2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            baiaJFT3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        baiaJFT3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            baiaJFT4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        baiaJFT4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            baiaJFT5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        baiaJFT5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            baiaJFT6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        baiaJFT6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            baiaJFT7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        baiaJFT7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            baiaJFT8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        baiaJFT8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            baiaJFT9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        baiaJFT9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            baiaJFT10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        baiaJFT10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            consumoJFT1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        consumoJFT1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            consumoJFT2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        consumoJFT2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            consumoJFT3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        consumoJFT3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            consumoJFT4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        consumoJFT4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            consumoJFT5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        consumoJFT5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            consumoJFT6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        consumoJFT6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            consumoJFT7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        consumoJFT7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            consumoJFT8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        consumoJFT8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            consumoJFT9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        consumoJFT9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            consumoJFT10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        consumoJFT10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Baia");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Consumo");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Controle");
        try {
            controleJFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        controleJFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ordemJFT1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemJFT7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemJFT2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemJFT8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemJFT5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemJFT9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemJFT6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemJFT4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemJFT3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ordemJFT10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout pnlConsTLayout = new javax.swing.GroupLayout(pnlConsT);
        pnlConsTLayout.setHorizontalGroup(
        	pnlConsTLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnlConsTLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(pnlConsTLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(pnlConsTLayout.createSequentialGroup()
        					.addGroup(pnlConsTLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(ordemJFT1, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ordemJFT2, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ordemJFT3, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ordemJFT4, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ordemJFT5, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ordemJFT6, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ordemJFT7, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ordemJFT8, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ordemJFT9, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ordemJFT10, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
        					.addGap(6)
        					.addGroup(pnlConsTLayout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(baiaJFT5)
        						.addComponent(baiaJFT9, Alignment.LEADING)
        						.addComponent(baiaJFT8, Alignment.LEADING)
        						.addComponent(baiaJFT7, Alignment.LEADING)
        						.addComponent(baiaJFT6, Alignment.LEADING)
        						.addComponent(baiaJFT4, Alignment.LEADING)
        						.addComponent(baiaJFT3, Alignment.LEADING)
        						.addComponent(baiaJFT2, Alignment.LEADING)
        						.addComponent(baiaJFT1, Alignment.LEADING)
        						.addComponent(baiaJFT10, GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(pnlConsTLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(consumoJFT5, 56, 56, 56)
        						.addComponent(consumoJFT9, 56, 56, 56)
        						.addComponent(consumoJFT8, 56, 56, 56)
        						.addComponent(consumoJFT7, 56, 56, 56)
        						.addComponent(consumoJFT6, 56, 56, 56)
        						.addComponent(consumoJFT4, 56, 56, 56)
        						.addComponent(consumoJFT2, 56, 56, 56)
        						.addComponent(consumoJFT3, 56, 56, 56)
        						.addComponent(consumoJFT1, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        						.addComponent(consumoJFT10, 56, 56, 56)))
        				.addGroup(pnlConsTLayout.createSequentialGroup()
        					.addComponent(jLabel9)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jLabel10)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jLabel11, GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(pnlConsTLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
        				.addComponent(controleJFT, 81, 81, 81))
        			.addContainerGap())
        );
        pnlConsTLayout.setVerticalGroup(
        	pnlConsTLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(pnlConsTLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(pnlConsTLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel9)
        				.addComponent(jLabel10)
        				.addComponent(jLabel11))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(pnlConsTLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(pnlConsTLayout.createSequentialGroup()
        					.addGap(0, 0, Short.MAX_VALUE)
        					.addComponent(baiaJFT1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(baiaJFT2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(baiaJFT3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(baiaJFT4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(32)
        					.addComponent(baiaJFT6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(baiaJFT7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(baiaJFT8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(baiaJFT9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(pnlConsTLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(baiaJFT10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(consumoJFT10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(controleJFT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(pnlConsTLayout.createSequentialGroup()
        					.addGap(0, 0, Short.MAX_VALUE)
        					.addComponent(consumoJFT1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(consumoJFT2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(consumoJFT3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(consumoJFT4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(pnlConsTLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(baiaJFT5, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        						.addComponent(consumoJFT5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(consumoJFT6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(consumoJFT7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(consumoJFT8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(pnlConsTLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(consumoJFT9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel12))
        					.addGap(26))
        				.addGroup(pnlConsTLayout.createSequentialGroup()
        					.addGap(0, 0, Short.MAX_VALUE)
        					.addComponent(ordemJFT1, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(ordemJFT2, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(ordemJFT3, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(ordemJFT4, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(ordemJFT5, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(ordemJFT6, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(ordemJFT7, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(ordemJFT8, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(ordemJFT9, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(ordemJFT10, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        pnlConsT.setLayout(pnlConsTLayout);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConsT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConsT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrosLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(baiaJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(baiaJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(registrosLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConsumoTST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConsumoTST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConsumoTST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConsumoTST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewConsumoTST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baiaHist1;
    private javax.swing.JLabel baiaHist10;
    private javax.swing.JLabel baiaHist2;
    private javax.swing.JLabel baiaHist3;
    private javax.swing.JLabel baiaHist4;
    private javax.swing.JLabel baiaHist5;
    private javax.swing.JLabel baiaHist6;
    private javax.swing.JLabel baiaHist7;
    private javax.swing.JLabel baiaHist8;
    private javax.swing.JLabel baiaHist9;
    private javax.swing.JFormattedTextField baiaJFT1;
    private javax.swing.JFormattedTextField baiaJFT10;
    private javax.swing.JFormattedTextField baiaJFT2;
    private javax.swing.JFormattedTextField baiaJFT3;
    private javax.swing.JFormattedTextField baiaJFT4;
    private javax.swing.JFormattedTextField baiaJFT5;
    private javax.swing.JFormattedTextField baiaJFT6;
    private javax.swing.JFormattedTextField baiaJFT7;
    private javax.swing.JFormattedTextField baiaJFT8;
    private javax.swing.JFormattedTextField baiaJFT9;
    private javax.swing.JPanel baiaJP;
    private javax.swing.JLabel consumoHist1;
    private javax.swing.JLabel consumoHist10;
    private javax.swing.JLabel consumoHist2;
    private javax.swing.JLabel consumoHist3;
    private javax.swing.JLabel consumoHist4;
    private javax.swing.JLabel consumoHist5;
    private javax.swing.JLabel consumoHist6;
    private javax.swing.JLabel consumoHist7;
    private javax.swing.JLabel consumoHist8;
    private javax.swing.JLabel consumoHist9;
    private javax.swing.JFormattedTextField consumoJFT1;
    private javax.swing.JFormattedTextField consumoJFT10;
    private javax.swing.JFormattedTextField consumoJFT2;
    private javax.swing.JFormattedTextField consumoJFT3;
    private javax.swing.JFormattedTextField consumoJFT4;
    private javax.swing.JFormattedTextField consumoJFT5;
    private javax.swing.JFormattedTextField consumoJFT6;
    private javax.swing.JFormattedTextField consumoJFT7;
    private javax.swing.JFormattedTextField consumoJFT8;
    private javax.swing.JFormattedTextField consumoJFT9;
    private javax.swing.JFormattedTextField controleJFT;
    private javax.swing.JFormattedTextField dataJFT;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JFormattedTextField opcaoJFT;
    private javax.swing.JLabel ordemHist1;
    private javax.swing.JLabel ordemHist10;
    private javax.swing.JLabel ordemHist2;
    private javax.swing.JLabel ordemHist3;
    private javax.swing.JLabel ordemHist4;
    private javax.swing.JLabel ordemHist5;
    private javax.swing.JLabel ordemHist6;
    private javax.swing.JLabel ordemHist7;
    private javax.swing.JLabel ordemHist8;
    private javax.swing.JLabel ordemHist9;
    private javax.swing.JLabel ordemJFT1;
    private javax.swing.JLabel ordemJFT10;
    private javax.swing.JLabel ordemJFT2;
    private javax.swing.JLabel ordemJFT3;
    private javax.swing.JLabel ordemJFT4;
    private javax.swing.JLabel ordemJFT5;
    private javax.swing.JLabel ordemJFT6;
    private javax.swing.JLabel ordemJFT7;
    private javax.swing.JLabel ordemJFT8;
    private javax.swing.JLabel ordemJFT9;
    private javax.swing.JPanel pnlConsT;
    private javax.swing.JLabel registrosLabel;
    private javax.swing.JFormattedTextField tratosJFT;
    // End of variables declaration//GEN-END:variables


	public javax.swing.JLabel getBaiaHist1() {
		return baiaHist1;
	}


	public void setBaiaHist1(javax.swing.JLabel baiaHist1) {
		this.baiaHist1 = baiaHist1;
	}


	public javax.swing.JLabel getBaiaHist10() {
		return baiaHist10;
	}


	public void setBaiaHist10(javax.swing.JLabel baiaHist10) {
		this.baiaHist10 = baiaHist10;
	}


	public javax.swing.JLabel getBaiaHist2() {
		return baiaHist2;
	}


	public void setBaiaHist2(javax.swing.JLabel baiaHist2) {
		this.baiaHist2 = baiaHist2;
	}


	public javax.swing.JLabel getBaiaHist3() {
		return baiaHist3;
	}


	public void setBaiaHist3(javax.swing.JLabel baiaHist3) {
		this.baiaHist3 = baiaHist3;
	}


	public javax.swing.JLabel getBaiaHist4() {
		return baiaHist4;
	}


	public void setBaiaHist4(javax.swing.JLabel baiaHist4) {
		this.baiaHist4 = baiaHist4;
	}


	public javax.swing.JLabel getBaiaHist5() {
		return baiaHist5;
	}


	public void setBaiaHist5(javax.swing.JLabel baiaHist5) {
		this.baiaHist5 = baiaHist5;
	}


	public javax.swing.JLabel getBaiaHist6() {
		return baiaHist6;
	}


	public void setBaiaHist6(javax.swing.JLabel baiaHist6) {
		this.baiaHist6 = baiaHist6;
	}


	public javax.swing.JLabel getBaiaHist7() {
		return baiaHist7;
	}


	public void setBaiaHist7(javax.swing.JLabel baiaHist7) {
		this.baiaHist7 = baiaHist7;
	}


	public javax.swing.JLabel getBaiaHist8() {
		return baiaHist8;
	}


	public void setBaiaHist8(javax.swing.JLabel baiaHist8) {
		this.baiaHist8 = baiaHist8;
	}


	public javax.swing.JLabel getBaiaHist9() {
		return baiaHist9;
	}


	public void setBaiaHist9(javax.swing.JLabel baiaHist9) {
		this.baiaHist9 = baiaHist9;
	}


	public javax.swing.JFormattedTextField getBaiaJFT1() {
		return baiaJFT1;
	}


	public void setBaiaJFT1(javax.swing.JFormattedTextField baiaJFT1) {
		this.baiaJFT1 = baiaJFT1;
	}


	public javax.swing.JFormattedTextField getBaiaJFT10() {
		return baiaJFT10;
	}


	public void setBaiaJFT10(javax.swing.JFormattedTextField baiaJFT10) {
		this.baiaJFT10 = baiaJFT10;
	}


	public javax.swing.JFormattedTextField getBaiaJFT2() {
		return baiaJFT2;
	}


	public void setBaiaJFT2(javax.swing.JFormattedTextField baiaJFT2) {
		this.baiaJFT2 = baiaJFT2;
	}


	public javax.swing.JFormattedTextField getBaiaJFT3() {
		return baiaJFT3;
	}


	public void setBaiaJFT3(javax.swing.JFormattedTextField baiaJFT3) {
		this.baiaJFT3 = baiaJFT3;
	}


	public javax.swing.JFormattedTextField getBaiaJFT4() {
		return baiaJFT4;
	}


	public void setBaiaJFT4(javax.swing.JFormattedTextField baiaJFT4) {
		this.baiaJFT4 = baiaJFT4;
	}


	public javax.swing.JFormattedTextField getBaiaJFT5() {
		return baiaJFT5;
	}


	public void setBaiaJFT5(javax.swing.JFormattedTextField baiaJFT5) {
		this.baiaJFT5 = baiaJFT5;
	}


	public javax.swing.JFormattedTextField getBaiaJFT6() {
		return baiaJFT6;
	}


	public void setBaiaJFT6(javax.swing.JFormattedTextField baiaJFT6) {
		this.baiaJFT6 = baiaJFT6;
	}


	public javax.swing.JFormattedTextField getBaiaJFT7() {
		return baiaJFT7;
	}


	public void setBaiaJFT7(javax.swing.JFormattedTextField baiaJFT7) {
		this.baiaJFT7 = baiaJFT7;
	}


	public javax.swing.JFormattedTextField getBaiaJFT8() {
		return baiaJFT8;
	}


	public void setBaiaJFT8(javax.swing.JFormattedTextField baiaJFT8) {
		this.baiaJFT8 = baiaJFT8;
	}


	public javax.swing.JFormattedTextField getBaiaJFT9() {
		return baiaJFT9;
	}


	public void setBaiaJFT9(javax.swing.JFormattedTextField baiaJFT9) {
		this.baiaJFT9 = baiaJFT9;
	}


	public javax.swing.JPanel getBaiaJP() {
		return baiaJP;
	}


	public void setBaiaJP(javax.swing.JPanel baiaJP) {
		this.baiaJP = baiaJP;
	}


	public javax.swing.JLabel getConsumoHist1() {
		return consumoHist1;
	}


	public void setConsumoHist1(javax.swing.JLabel consumoHist1) {
		this.consumoHist1 = consumoHist1;
	}


	public javax.swing.JLabel getConsumoHist10() {
		return consumoHist10;
	}


	public void setConsumoHist10(javax.swing.JLabel consumoHist10) {
		this.consumoHist10 = consumoHist10;
	}


	public javax.swing.JLabel getConsumoHist2() {
		return consumoHist2;
	}


	public void setConsumoHist2(javax.swing.JLabel consumoHist2) {
		this.consumoHist2 = consumoHist2;
	}


	public javax.swing.JLabel getConsumoHist3() {
		return consumoHist3;
	}


	public void setConsumoHist3(javax.swing.JLabel consumoHist3) {
		this.consumoHist3 = consumoHist3;
	}


	public javax.swing.JLabel getConsumoHist4() {
		return consumoHist4;
	}


	public void setConsumoHist4(javax.swing.JLabel consumoHist4) {
		this.consumoHist4 = consumoHist4;
	}


	public javax.swing.JLabel getConsumoHist5() {
		return consumoHist5;
	}


	public void setConsumoHist5(javax.swing.JLabel consumoHist5) {
		this.consumoHist5 = consumoHist5;
	}


	public javax.swing.JLabel getConsumoHist6() {
		return consumoHist6;
	}


	public void setConsumoHist6(javax.swing.JLabel consumoHist6) {
		this.consumoHist6 = consumoHist6;
	}


	public javax.swing.JLabel getConsumoHist7() {
		return consumoHist7;
	}


	public void setConsumoHist7(javax.swing.JLabel consumoHist7) {
		this.consumoHist7 = consumoHist7;
	}


	public javax.swing.JLabel getConsumoHist8() {
		return consumoHist8;
	}


	public void setConsumoHist8(javax.swing.JLabel consumoHist8) {
		this.consumoHist8 = consumoHist8;
	}


	public javax.swing.JLabel getConsumoHist9() {
		return consumoHist9;
	}


	public void setConsumoHist9(javax.swing.JLabel consumoHist9) {
		this.consumoHist9 = consumoHist9;
	}


	public javax.swing.JFormattedTextField getConsumoJFT1() {
		return consumoJFT1;
	}


	public void setConsumoJFT1(javax.swing.JFormattedTextField consumoJFT1) {
		this.consumoJFT1 = consumoJFT1;
	}


	public javax.swing.JFormattedTextField getConsumoJFT10() {
		return consumoJFT10;
	}


	public void setConsumoJFT10(javax.swing.JFormattedTextField consumoJFT10) {
		this.consumoJFT10 = consumoJFT10;
	}


	public javax.swing.JFormattedTextField getConsumoJFT2() {
		return consumoJFT2;
	}


	public void setConsumoJFT2(javax.swing.JFormattedTextField consumoJFT2) {
		this.consumoJFT2 = consumoJFT2;
	}


	public javax.swing.JFormattedTextField getConsumoJFT3() {
		return consumoJFT3;
	}


	public void setConsumoJFT3(javax.swing.JFormattedTextField consumoJFT3) {
		this.consumoJFT3 = consumoJFT3;
	}


	public javax.swing.JFormattedTextField getConsumoJFT4() {
		return consumoJFT4;
	}


	public void setConsumoJFT4(javax.swing.JFormattedTextField consumoJFT4) {
		this.consumoJFT4 = consumoJFT4;
	}


	public javax.swing.JFormattedTextField getConsumoJFT5() {
		return consumoJFT5;
	}


	public void setConsumoJFT5(javax.swing.JFormattedTextField consumoJFT5) {
		this.consumoJFT5 = consumoJFT5;
	}


	public javax.swing.JFormattedTextField getConsumoJFT6() {
		return consumoJFT6;
	}


	public void setConsumoJFT6(javax.swing.JFormattedTextField consumoJFT6) {
		this.consumoJFT6 = consumoJFT6;
	}


	public javax.swing.JFormattedTextField getConsumoJFT7() {
		return consumoJFT7;
	}


	public void setConsumoJFT7(javax.swing.JFormattedTextField consumoJFT7) {
		this.consumoJFT7 = consumoJFT7;
	}


	public javax.swing.JFormattedTextField getConsumoJFT8() {
		return consumoJFT8;
	}


	public void setConsumoJFT8(javax.swing.JFormattedTextField consumoJFT8) {
		this.consumoJFT8 = consumoJFT8;
	}


	public javax.swing.JFormattedTextField getConsumoJFT9() {
		return consumoJFT9;
	}


	public void setConsumoJFT9(javax.swing.JFormattedTextField consumoJFT9) {
		this.consumoJFT9 = consumoJFT9;
	}


	public javax.swing.JFormattedTextField getControleJFT() {
		return controleJFT;
	}


	public void setControleJFT(javax.swing.JFormattedTextField controleJFT) {
		this.controleJFT = controleJFT;
	}


	public javax.swing.JFormattedTextField getDataJFT() {
		return dataJFT;
	}


	public void setDataJFT(javax.swing.JFormattedTextField dataJFT) {
		this.dataJFT = dataJFT;
	}


	public javax.swing.JLabel getjLabel10() {
		return jLabel10;
	}


	public void setjLabel10(javax.swing.JLabel jLabel10) {
		this.jLabel10 = jLabel10;
	}


	public javax.swing.JLabel getjLabel11() {
		return jLabel11;
	}


	public void setjLabel11(javax.swing.JLabel jLabel11) {
		this.jLabel11 = jLabel11;
	}


	public javax.swing.JLabel getjLabel12() {
		return jLabel12;
	}


	public void setjLabel12(javax.swing.JLabel jLabel12) {
		this.jLabel12 = jLabel12;
	}


	public javax.swing.JLabel getjLabel24() {
		return jLabel24;
	}


	public void setjLabel24(javax.swing.JLabel jLabel24) {
		this.jLabel24 = jLabel24;
	}


	public javax.swing.JLabel getjLabel25() {
		return jLabel25;
	}


	public void setjLabel25(javax.swing.JLabel jLabel25) {
		this.jLabel25 = jLabel25;
	}


	public javax.swing.JLabel getjLabel44() {
		return jLabel44;
	}


	public void setjLabel44(javax.swing.JLabel jLabel44) {
		this.jLabel44 = jLabel44;
	}


	public javax.swing.JLabel getjLabel50() {
		return jLabel50;
	}


	public void setjLabel50(javax.swing.JLabel jLabel50) {
		this.jLabel50 = jLabel50;
	}


	public javax.swing.JLabel getjLabel51() {
		return jLabel51;
	}


	public void setjLabel51(javax.swing.JLabel jLabel51) {
		this.jLabel51 = jLabel51;
	}


	public javax.swing.JLabel getjLabel77() {
		return jLabel77;
	}


	public void setjLabel77(javax.swing.JLabel jLabel77) {
		this.jLabel77 = jLabel77;
	}


	public javax.swing.JLabel getjLabel78() {
		return jLabel78;
	}


	public void setjLabel78(javax.swing.JLabel jLabel78) {
		this.jLabel78 = jLabel78;
	}


	public javax.swing.JLabel getjLabel8() {
		return jLabel8;
	}


	public void setjLabel8(javax.swing.JLabel jLabel8) {
		this.jLabel8 = jLabel8;
	}


	public javax.swing.JLabel getjLabel9() {
		return jLabel9;
	}


	public void setjLabel9(javax.swing.JLabel jLabel9) {
		this.jLabel9 = jLabel9;
	}


	public javax.swing.JPanel getjPanel1() {
		return jPanel1;
	}


	public void setjPanel1(javax.swing.JPanel jPanel1) {
		this.jPanel1 = jPanel1;
	}


	public javax.swing.JPanel getjPanel2() {
		return jPanel2;
	}


	public void setjPanel2(javax.swing.JPanel jPanel2) {
		this.jPanel2 = jPanel2;
	}


	public javax.swing.JPanel getjPanel3() {
		return jPanel3;
	}


	public void setjPanel3(javax.swing.JPanel jPanel3) {
		this.jPanel3 = jPanel3;
	}


	public javax.swing.JPanel getjPanel4() {
		return jPanel4;
	}


	public void setjPanel4(javax.swing.JPanel jPanel4) {
		this.jPanel4 = jPanel4;
	}


	public javax.swing.JPanel getjPanel7() {
		return jPanel7;
	}


	public void setjPanel7(javax.swing.JPanel jPanel7) {
		this.jPanel7 = jPanel7;
	}


	public javax.swing.JFormattedTextField getOpcaoJFT() {
		return opcaoJFT;
	}


	public void setOpcaoJFT(javax.swing.JFormattedTextField opcaoJFT) {
		this.opcaoJFT = opcaoJFT;
	}


	public javax.swing.JLabel getOrdemHist1() {
		return ordemHist1;
	}


	public void setOrdemHist1(javax.swing.JLabel ordemHist1) {
		this.ordemHist1 = ordemHist1;
	}


	public javax.swing.JLabel getOrdemHist10() {
		return ordemHist10;
	}


	public void setOrdemHist10(javax.swing.JLabel ordemHist10) {
		this.ordemHist10 = ordemHist10;
	}


	public javax.swing.JLabel getOrdemHist2() {
		return ordemHist2;
	}


	public void setOrdemHist2(javax.swing.JLabel ordemHist2) {
		this.ordemHist2 = ordemHist2;
	}


	public javax.swing.JLabel getOrdemHist3() {
		return ordemHist3;
	}


	public void setOrdemHist3(javax.swing.JLabel ordemHist3) {
		this.ordemHist3 = ordemHist3;
	}


	public javax.swing.JLabel getOrdemHist4() {
		return ordemHist4;
	}


	public void setOrdemHist4(javax.swing.JLabel ordemHist4) {
		this.ordemHist4 = ordemHist4;
	}


	public javax.swing.JLabel getOrdemHist5() {
		return ordemHist5;
	}


	public void setOrdemHist5(javax.swing.JLabel ordemHist5) {
		this.ordemHist5 = ordemHist5;
	}


	public javax.swing.JLabel getOrdemHist6() {
		return ordemHist6;
	}


	public void setOrdemHist6(javax.swing.JLabel ordemHist6) {
		this.ordemHist6 = ordemHist6;
	}


	public javax.swing.JLabel getOrdemHist7() {
		return ordemHist7;
	}


	public void setOrdemHist7(javax.swing.JLabel ordemHist7) {
		this.ordemHist7 = ordemHist7;
	}


	public javax.swing.JLabel getOrdemHist8() {
		return ordemHist8;
	}


	public void setOrdemHist8(javax.swing.JLabel ordemHist8) {
		this.ordemHist8 = ordemHist8;
	}


	public javax.swing.JLabel getOrdemHist9() {
		return ordemHist9;
	}


	public void setOrdemHist9(javax.swing.JLabel ordemHist9) {
		this.ordemHist9 = ordemHist9;
	}


	public javax.swing.JLabel getOrdemJFT1() {
		return ordemJFT1;
	}


	public void setOrdemJFT1(javax.swing.JLabel ordemJFT1) {
		this.ordemJFT1 = ordemJFT1;
	}


	public javax.swing.JLabel getOrdemJFT10() {
		return ordemJFT10;
	}


	public void setOrdemJFT10(javax.swing.JLabel ordemJFT10) {
		this.ordemJFT10 = ordemJFT10;
	}


	public javax.swing.JLabel getOrdemJFT2() {
		return ordemJFT2;
	}


	public void setOrdemJFT2(javax.swing.JLabel ordemJFT2) {
		this.ordemJFT2 = ordemJFT2;
	}


	public javax.swing.JLabel getOrdemJFT3() {
		return ordemJFT3;
	}


	public void setOrdemJFT3(javax.swing.JLabel ordemJFT3) {
		this.ordemJFT3 = ordemJFT3;
	}


	public javax.swing.JLabel getOrdemJFT4() {
		return ordemJFT4;
	}


	public void setOrdemJFT4(javax.swing.JLabel ordemJFT4) {
		this.ordemJFT4 = ordemJFT4;
	}


	public javax.swing.JLabel getOrdemJFT5() {
		return ordemJFT5;
	}


	public void setOrdemJFT5(javax.swing.JLabel ordemJFT5) {
		this.ordemJFT5 = ordemJFT5;
	}


	public javax.swing.JLabel getOrdemJFT6() {
		return ordemJFT6;
	}


	public void setOrdemJFT6(javax.swing.JLabel ordemJFT6) {
		this.ordemJFT6 = ordemJFT6;
	}


	public javax.swing.JLabel getOrdemJFT7() {
		return ordemJFT7;
	}


	public void setOrdemJFT7(javax.swing.JLabel ordemJFT7) {
		this.ordemJFT7 = ordemJFT7;
	}


	public javax.swing.JLabel getOrdemJFT8() {
		return ordemJFT8;
	}


	public void setOrdemJFT8(javax.swing.JLabel ordemJFT8) {
		this.ordemJFT8 = ordemJFT8;
	}


	public javax.swing.JLabel getOrdemJFT9() {
		return ordemJFT9;
	}


	public void setOrdemJFT9(javax.swing.JLabel ordemJFT9) {
		this.ordemJFT9 = ordemJFT9;
	}


	public javax.swing.JPanel getPnlConsT() {
		return pnlConsT;
	}


	public void setPnlConsT(javax.swing.JPanel pnlConsT) {
		this.pnlConsT = pnlConsT;
	}


	public javax.swing.JLabel getRegistrosLabel() {
		return registrosLabel;
	}


	public void setRegistrosLabel(javax.swing.JLabel registrosLabel) {
		this.registrosLabel = registrosLabel;
	}


	public javax.swing.JFormattedTextField getTratosJFT() {
		return tratosJFT;
	}


	public void setTratosJFT(javax.swing.JFormattedTextField tratosJFT) {
		this.tratosJFT = tratosJFT;
	}


	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	


}
