package brf.suino.view;

import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class ViewConsumoTratosST extends javax.swing.JFrame {
	public ViewConsumoTratosST() {
		initComponents();
	}

	public JFormattedTextField getAviarioJFT() {
		return aviarioJFT;
	}

	public JPanel getConeJP() {
		return coneJP;
	}

	public JFormattedTextField getControleJFT() {
		return controleJFT;
	}

	public JFormattedTextField getDataAbateJFT() {
		return dataAbateJFT;
	}

	public JLabel getNumHist1Label() {
		return numHist1Label;
	}

	public JLabel getNumHist2Label() {
		return numHist2Label;
	}

	public JLabel getNumHist3Label() {
		return numHist3Label;
	}

	public JLabel getNumHist4Label() {
		return numHist4Label;
	}

	public JLabel getNumHist5Label() {
		return numHist5Label;
	}

	public JLabel getOrdemHist1Label() {
		return ordemHist1Label;
	}

	public JLabel getOrdemHist2Label() {
		return ordemHist2Label;
	}

	public JLabel getOrdemHist3Label() {
		return ordemHist3Label;
	}

	public JLabel getOrdemHist4Label() {
		return ordemHist4Label;
	}

	public JLabel getOrdemHist5Label() {
		return ordemHist5Label;
	}

	public JFormattedTextField getpCoxa5JFT() {
		return pCoxa5JFT;
	}

	public JLabel getpCoxaHist1Label() {
		return pCoxaHist1Label;
	}

	public JLabel getpCoxaHist2Label() {
		return pCoxaHist2Label;
	}

	public JLabel getpCoxaHist3Label() {
		return pCoxaHist3Label;
	}

	public JLabel getpCoxaHist4Label() {
		return pCoxaHist4Label;
	}

	public JLabel getpCoxaHist5Label() {
		return pCoxaHist5Label;
	}

	public JLabel getpGordHist1Label() {
		return pGordHist1Label;
	}

	public JLabel getpGordHist2Label() {
		return pGordHist2Label;
	}

	public JLabel getpGordHist3Label() {
		return pGordHist3Label;
	}

	public JLabel getpGordHist4Label() {
		return pGordHist4Label;
	}

	public JLabel getpGordHist5Label() {
		return pGordHist5Label;
	}

	public JLabel getpPeito1Hist1Label() {
		return pPeito1Hist1Label;
	}

	public JLabel getpPeito1Hist2Label() {
		return pPeito1Hist2Label;
	}

	public JLabel getpPeito1Hist3Label() {
		return pPeito1Hist3Label;
	}

	public JLabel getpPeito1Hist4Label() {
		return pPeito1Hist4Label;
	}

	public JLabel getpPeito1Hist5Label() {
		return pPeito1Hist5Label;
	}

	public JLabel getRegistrosLabel() {
		return registrosLabel;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		coneJP = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		controleJFT = new javax.swing.JFormattedTextField();
		ordemHist1Label = new javax.swing.JLabel();
		ordemHist2Label = new javax.swing.JLabel();
		numHist1Label = new javax.swing.JLabel();
		numHist2Label = new javax.swing.JLabel();
		pGordHist1Label = new javax.swing.JLabel();
		pGordHist2Label = new javax.swing.JLabel();
		pPeito1Hist1Label = new javax.swing.JLabel();
		pPeito1Hist2Label = new javax.swing.JLabel();
		pPeito2Hist1Label = new javax.swing.JLabel();
		pPeito2Hist2Label = new javax.swing.JLabel();
		ordemHist3Label = new javax.swing.JLabel();
		numHist3Label = new javax.swing.JLabel();
		pGordHist3Label = new javax.swing.JLabel();
		pPeito1Hist3Label = new javax.swing.JLabel();
		pPeito2Hist3Label = new javax.swing.JLabel();
		ordemHist4Label = new javax.swing.JLabel();
		numHist4Label = new javax.swing.JLabel();
		pGordHist4Label = new javax.swing.JLabel();
		pPeito1Hist4Label = new javax.swing.JLabel();
		pPeito2Hist4Label = new javax.swing.JLabel();
		ordemHist5Label = new javax.swing.JLabel();
		numHist5Label = new javax.swing.JLabel();
		pGordHist5Label = new javax.swing.JLabel();
		pPeito1Hist5Label = new javax.swing.JLabel();
		pPeito2Hist5Label = new javax.swing.JLabel();
		pCoxaHist1Label = new javax.swing.JLabel();
		pCoxaHist2Label = new javax.swing.JLabel();
		pCoxaHist3Label = new javax.swing.JLabel();
		pCoxaHist4Label = new javax.swing.JLabel();
		pCoxaHist5Label = new javax.swing.JLabel();
		pCoxa5JFT = new javax.swing.JFormattedTextField();
		pPeito25JFT = new javax.swing.JFormattedTextField();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		pPeito2Hist5Label1 = new javax.swing.JLabel();
		pCoxaHist5Label1 = new javax.swing.JLabel();
		pPeito1Hist5Label1 = new javax.swing.JLabel();
		pPeito1Hist4Label1 = new javax.swing.JLabel();
		pPeito2Hist4Label1 = new javax.swing.JLabel();
		pCoxaHist4Label1 = new javax.swing.JLabel();
		pCoxaHist3Label1 = new javax.swing.JLabel();
		pPeito2Hist3Label1 = new javax.swing.JLabel();
		pPeito1Hist3Label1 = new javax.swing.JLabel();
		pPeito1Hist2Label1 = new javax.swing.JLabel();
		pPeito2Hist2Label1 = new javax.swing.JLabel();
		pCoxaHist2Label1 = new javax.swing.JLabel();
		pCoxaHist1Label1 = new javax.swing.JLabel();
		pPeito2Hist1Label1 = new javax.swing.JLabel();
		pPeito1Hist1Label1 = new javax.swing.JLabel();
		ordemHist5Label1 = new javax.swing.JLabel();
		numHist5Label1 = new javax.swing.JLabel();
		pGordHist5Label1 = new javax.swing.JLabel();
		pGordHist4Label1 = new javax.swing.JLabel();
		numHist4Label1 = new javax.swing.JLabel();
		ordemHist4Label1 = new javax.swing.JLabel();
		ordemHist3Label1 = new javax.swing.JLabel();
		numHist3Label1 = new javax.swing.JLabel();
		pGordHist3Label1 = new javax.swing.JLabel();
		pGordHist2Label1 = new javax.swing.JLabel();
		numHist2Label1 = new javax.swing.JLabel();
		ordemHist2Label1 = new javax.swing.JLabel();
		ordemHist1Label1 = new javax.swing.JLabel();
		numHist1Label1 = new javax.swing.JLabel();
		pGordHist1Label1 = new javax.swing.JLabel();
		numHist1Label2 = new javax.swing.JLabel();
		registrosLabel = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		aviarioJFT = new javax.swing.JFormattedTextField();
		jLabel22 = new javax.swing.JLabel();
		dataAbateJFT = new javax.swing.JFormattedTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		coneJP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

		jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel12.setText("Controle");

		try {
			controleJFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		controleJFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		controleJFT.setEnabled(false);

		ordemHist1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		ordemHist1Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		ordemHist2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		ordemHist2Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		numHist1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		numHist1Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		numHist2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		numHist2Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pGordHist1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pGordHist1Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pGordHist2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pGordHist2Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito1Hist1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito1Hist1Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito1Hist2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito1Hist2Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito2Hist1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito2Hist1Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito2Hist2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito2Hist2Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		ordemHist3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		ordemHist3Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		numHist3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		numHist3Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pGordHist3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pGordHist3Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito1Hist3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito1Hist3Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito2Hist3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito2Hist3Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		ordemHist4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		ordemHist4Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		numHist4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		numHist4Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pGordHist4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pGordHist4Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito1Hist4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito1Hist4Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito2Hist4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito2Hist4Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		ordemHist5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		ordemHist5Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		numHist5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		numHist5Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pGordHist5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pGordHist5Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito1Hist5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito1Hist5Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito2Hist5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito2Hist5Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pCoxaHist1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pCoxaHist1Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pCoxaHist2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pCoxaHist2Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pCoxaHist3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pCoxaHist3Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pCoxaHist4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pCoxaHist4Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pCoxaHist5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pCoxaHist5Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		try {
			pCoxa5JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		pCoxa5JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		pCoxa5JFT.setEnabled(false);

		try {
			pPeito25JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		pPeito25JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		pPeito25JFT.setEnabled(false);

		jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel13.setText("Ordem");

		jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel14.setText("Baia");

		jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel15.setText("Consumo");

		pPeito2Hist5Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito2Hist5Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pCoxaHist5Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pCoxaHist5Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito1Hist5Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito1Hist5Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito1Hist4Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito1Hist4Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito2Hist4Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito2Hist4Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pCoxaHist4Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pCoxaHist4Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pCoxaHist3Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pCoxaHist3Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito2Hist3Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito2Hist3Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito1Hist3Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito1Hist3Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito1Hist2Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito1Hist2Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito2Hist2Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito2Hist2Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pCoxaHist2Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pCoxaHist2Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pCoxaHist1Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pCoxaHist1Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito2Hist1Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito2Hist1Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pPeito1Hist1Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pPeito1Hist1Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		ordemHist5Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		ordemHist5Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		numHist5Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		numHist5Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pGordHist5Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pGordHist5Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pGordHist4Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pGordHist4Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		numHist4Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		numHist4Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		ordemHist4Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		ordemHist4Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		ordemHist3Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		ordemHist3Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		numHist3Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		numHist3Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pGordHist3Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pGordHist3Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pGordHist2Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pGordHist2Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		numHist2Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		numHist2Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		ordemHist2Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		ordemHist2Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		ordemHist1Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		ordemHist1Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		numHist1Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		numHist1Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pGordHist1Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pGordHist1Label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		numHist1Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		numHist1Label2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		javax.swing.GroupLayout coneJPLayout = new javax.swing.GroupLayout(coneJP);
		coneJP.setLayout(coneJPLayout);
		coneJPLayout.setHorizontalGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(coneJPLayout
				.createSequentialGroup().addContainerGap()
				.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(coneJPLayout
						.createSequentialGroup()
						.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(pPeito1Hist4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(pPeito1Hist3Label, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pPeito1Hist2Label, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pPeito1Hist1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(pPeito1Hist5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(coneJPLayout.createSequentialGroup()
										.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(pPeito2Hist4Label, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pPeito2Hist5Label, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pPeito2Hist3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(pCoxaHist3Label, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pCoxaHist4Label, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pCoxaHist5Label, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coneJPLayout.createSequentialGroup()
										.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(pPeito2Hist1Label, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pPeito2Hist2Label, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(pCoxaHist1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
												.addComponent(pCoxaHist2Label, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
						.addGroup(coneJPLayout.createSequentialGroup()
								.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(ordemHist1Label, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(ordemHist2Label, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(ordemHist3Label, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(ordemHist4Label, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(
												ordemHist5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(numHist4Label, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
										.addComponent(numHist3Label, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(numHist2Label, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(numHist5Label, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(pGordHist2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
										.addComponent(pGordHist3Label, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(pGordHist4Label, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(pGordHist5Label, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(pGordHist1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 56,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING, coneJPLayout.createSequentialGroup()
										.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(numHist1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
														coneJPLayout.createSequentialGroup()
																.addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel15,
												javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(coneJPLayout
						.createSequentialGroup()
						.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(pPeito1Hist4Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pPeito1Hist3Label1, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pPeito1Hist2Label1, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pPeito1Hist1Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pPeito1Hist5Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coneJPLayout.createSequentialGroup()
										.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(pPeito2Hist1Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pPeito2Hist2Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(pCoxaHist1Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pCoxaHist2Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 56,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(coneJPLayout.createSequentialGroup().addGroup(coneJPLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(pPeito25JFT, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(pPeito2Hist4Label1, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(pPeito2Hist5Label1, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(pPeito2Hist3Label1, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(pCoxaHist3Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pCoxaHist4Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pCoxaHist5Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pCoxa5JFT)))))
						.addGroup(coneJPLayout.createSequentialGroup().addGroup(coneJPLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(ordemHist1Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(ordemHist2Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(ordemHist3Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(ordemHist4Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(ordemHist5Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(numHist1Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(coneJPLayout
										.createSequentialGroup()
										.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(numHist4Label1, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(numHist3Label1, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(numHist2Label1, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(numHist5Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(pGordHist2Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pGordHist3Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pGordHist4Label1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(pGordHist5Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 56,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(coneJPLayout.createSequentialGroup()
												.addComponent(numHist1Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(pGordHist1Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 56,
														javax.swing.GroupLayout.PREFERRED_SIZE)))))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(controleJFT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap()));
		coneJPLayout.setVerticalGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(coneJPLayout
				.createSequentialGroup().addContainerGap(12, Short.MAX_VALUE)
				.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel13)
						.addComponent(jLabel14).addComponent(jLabel15))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coneJPLayout.createSequentialGroup()
								.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(coneJPLayout.createSequentialGroup()
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(ordemHist1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(numHist1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pGordHist1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(ordemHist2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(numHist2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pGordHist2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(ordemHist3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(numHist3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pGordHist3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(ordemHist4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(numHist4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pGordHist4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(ordemHist5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(numHist5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pGordHist5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(12, 12, 12).addComponent(pCoxaHist1Label, javax.swing.GroupLayout.PREFERRED_SIZE,
														14, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(pPeito2Hist1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(pPeito1Hist1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												coneJPLayout.createSequentialGroup()
														.addComponent(pPeito1Hist2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(pPeito1Hist3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(pPeito1Hist4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(pPeito1Hist5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coneJPLayout.createSequentialGroup()
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(pPeito2Hist2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pCoxaHist2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(pPeito2Hist3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pCoxaHist3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(pPeito2Hist4Label, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pCoxaHist4Label, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(pPeito2Hist5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pCoxaHist5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addGroup(coneJPLayout.createSequentialGroup().addGroup(coneJPLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(pPeito1Hist1Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(coneJPLayout.createSequentialGroup()
										.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(ordemHist1Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(numHist1Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pGordHist1Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(numHist1Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														coneJPLayout.createSequentialGroup().addGroup(coneJPLayout
																.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(ordemHist2Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(numHist2Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		pGordHist2Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(coneJPLayout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(ordemHist3Label1,
																				javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				numHist3Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(pGordHist3Label1,
																				javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(coneJPLayout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(ordemHist4Label1,
																				javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				numHist4Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(pGordHist4Label1,
																				javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(coneJPLayout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(ordemHist5Label1,
																				javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(numHist5Label1,
																				javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(pGordHist5Label1,
																				javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(12, 12, 12).addComponent(pCoxaHist1Label1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(pPeito2Hist1Label1, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												coneJPLayout.createSequentialGroup()
														.addComponent(pPeito1Hist2Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(pPeito1Hist3Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(pPeito1Hist4Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(pPeito1Hist5Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coneJPLayout.createSequentialGroup()
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(pPeito2Hist2Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pCoxaHist2Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(pPeito2Hist3Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pCoxaHist3Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(pPeito2Hist4Label1, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pCoxaHist4Label1, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(pPeito2Hist5Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(pCoxaHist5Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																javax.swing.GroupLayout.PREFERRED_SIZE))))))
				.addGap(6, 6, 6)
				.addGroup(coneJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(pPeito25JFT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(pCoxa5JFT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(controleJFT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap()));

		registrosLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		registrosLabel.setForeground(new java.awt.Color(0, 153, 255));
		registrosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		registrosLabel.setText("Registros salvos com sucesso!!");

		jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

		jLabel10.setText("Aviário");

		aviarioJFT.setEditable(false);
		aviarioJFT.setForeground(new java.awt.Color(0, 153, 255));
		try {
			aviarioJFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		aviarioJFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);

		jLabel22.setText("Data");

		dataAbateJFT.setEditable(false);
		dataAbateJFT.setForeground(new java.awt.Color(0, 153, 255));
		try {
			dataAbateJFT
					.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		dataAbateJFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel22)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(dataAbateJFT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(29, 29, 29).addComponent(jLabel10).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(aviarioJFT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(19, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel10)
								.addComponent(aviarioJFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel22).addComponent(dataAbateJFT, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup().addContainerGap()
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout
						.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addGap(0, 2, Short.MAX_VALUE).addComponent(registrosLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap())
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(coneJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(coneJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(registrosLabel)
								.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
						.createSequentialGroup().addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
						.createSequentialGroup().addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ViewConsumoTratosST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ViewConsumoTratosST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ViewConsumoTratosST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ViewConsumoTratosST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ViewConsumoTratosST().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JFormattedTextField aviarioJFT;
	private javax.swing.JPanel coneJP;
	private javax.swing.JFormattedTextField controleJFT;
	private javax.swing.JFormattedTextField dataAbateJFT;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JLabel numHist1Label;
	private javax.swing.JLabel numHist1Label1;
	private javax.swing.JLabel numHist1Label2;
	private javax.swing.JLabel numHist2Label;
	private javax.swing.JLabel numHist2Label1;
	private javax.swing.JLabel numHist3Label;
	private javax.swing.JLabel numHist3Label1;
	private javax.swing.JLabel numHist4Label;
	private javax.swing.JLabel numHist4Label1;
	private javax.swing.JLabel numHist5Label;
	private javax.swing.JLabel numHist5Label1;
	private javax.swing.JLabel ordemHist1Label;
	private javax.swing.JLabel ordemHist1Label1;
	private javax.swing.JLabel ordemHist2Label;
	private javax.swing.JLabel ordemHist2Label1;
	private javax.swing.JLabel ordemHist3Label;
	private javax.swing.JLabel ordemHist3Label1;
	private javax.swing.JLabel ordemHist4Label;
	private javax.swing.JLabel ordemHist4Label1;
	private javax.swing.JLabel ordemHist5Label;
	private javax.swing.JLabel ordemHist5Label1;
	private javax.swing.JFormattedTextField pCoxa5JFT;
	private javax.swing.JLabel pCoxaHist1Label;
	private javax.swing.JLabel pCoxaHist1Label1;
	private javax.swing.JLabel pCoxaHist2Label;
	private javax.swing.JLabel pCoxaHist2Label1;
	private javax.swing.JLabel pCoxaHist3Label;
	private javax.swing.JLabel pCoxaHist3Label1;
	private javax.swing.JLabel pCoxaHist4Label;
	private javax.swing.JLabel pCoxaHist4Label1;
	private javax.swing.JLabel pCoxaHist5Label;
	private javax.swing.JLabel pCoxaHist5Label1;
	private javax.swing.JLabel pGordHist1Label;
	private javax.swing.JLabel pGordHist1Label1;
	private javax.swing.JLabel pGordHist2Label;
	private javax.swing.JLabel pGordHist2Label1;
	private javax.swing.JLabel pGordHist3Label;
	private javax.swing.JLabel pGordHist3Label1;
	private javax.swing.JLabel pGordHist4Label;
	private javax.swing.JLabel pGordHist4Label1;
	private javax.swing.JLabel pGordHist5Label;
	private javax.swing.JLabel pGordHist5Label1;
	private javax.swing.JLabel pPeito1Hist1Label;
	private javax.swing.JLabel pPeito1Hist1Label1;
	private javax.swing.JLabel pPeito1Hist2Label;
	private javax.swing.JLabel pPeito1Hist2Label1;
	private javax.swing.JLabel pPeito1Hist3Label;
	private javax.swing.JLabel pPeito1Hist3Label1;
	private javax.swing.JLabel pPeito1Hist4Label;
	private javax.swing.JLabel pPeito1Hist4Label1;
	private javax.swing.JLabel pPeito1Hist5Label;
	private javax.swing.JLabel pPeito1Hist5Label1;
	private javax.swing.JFormattedTextField pPeito25JFT;
	private javax.swing.JLabel pPeito2Hist1Label;
	private javax.swing.JLabel pPeito2Hist1Label1;
	private javax.swing.JLabel pPeito2Hist2Label;
	private javax.swing.JLabel pPeito2Hist2Label1;
	private javax.swing.JLabel pPeito2Hist3Label;
	private javax.swing.JLabel pPeito2Hist3Label1;
	private javax.swing.JLabel pPeito2Hist4Label;
	private javax.swing.JLabel pPeito2Hist4Label1;
	private javax.swing.JLabel pPeito2Hist5Label;
	private javax.swing.JLabel pPeito2Hist5Label1;
	private javax.swing.JLabel registrosLabel;
	// End of variables declaration//GEN-END:variables
}
