package brf.suino.view;

import java.text.ParseException;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;

public class ViewDigitarBarrigaST extends javax.swing.JFrame {

	

	/**
	 * Creates new form ViewImportarBalanca
	 */
	public ViewDigitarBarrigaST() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		tatuagemHist3 = new javax.swing.JLabel();
		jLabel42 = new javax.swing.JLabel();
		jLabel43 = new javax.swing.JLabel();
		jLabel45 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		baiaJP = new javax.swing.JPanel();
		jLabel44 = new javax.swing.JLabel();
		dataJFT = new javax.swing.JFormattedTextField();
		dataJFT.setForeground(new Color(30, 144, 255));
		registrosLabel = new javax.swing.JLabel();
		jPanel7 = new javax.swing.JPanel();
		jLabel24 = new javax.swing.JLabel();
		jLabel25 = new javax.swing.JLabel();
		jLabel50 = new javax.swing.JLabel();
		pnlBarriga = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		cptf3JFT = new javax.swing.JFormattedTextField();
		jLabel16 = new javax.swing.JLabel();
		pronta3JFT = new javax.swing.JFormattedTextField();
		peso3JFT = new javax.swing.JFormattedTextField();
		jLabel28 = new javax.swing.JLabel();
		tatuagemJFT3 = new javax.swing.JFormattedTextField();
		jLabel29 = new javax.swing.JLabel();
		controleJFT = new javax.swing.JFormattedTextField();
		jLabel35 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		esgor3JFT = new javax.swing.JFormattedTextField();
		tatuagemHist3_1 = new javax.swing.JLabel();
		tatuagemHist2 = new javax.swing.JLabel();
		tatuagemHist1 = new javax.swing.JLabel();
		pesoHist3 = new javax.swing.JLabel();
		pesoHist2 = new javax.swing.JLabel();
		pesoHist1 = new javax.swing.JLabel();
		cptfHist3 = new javax.swing.JLabel();
		cptfHist2 = new javax.swing.JLabel();
		cptfHist1 = new javax.swing.JLabel();
		prontaHist3 = new javax.swing.JLabel();
		prontaHist2 = new javax.swing.JLabel();
		prontaHist1 = new javax.swing.JLabel();
		esgorHist3 = new javax.swing.JLabel();
		esgorHist2 = new javax.swing.JLabel();
		esgorHist1 = new javax.swing.JLabel();
		tatuagemJFT2 = new javax.swing.JFormattedTextField();
		tatuagemJFT1 = new javax.swing.JFormattedTextField();
		peso2JFT = new javax.swing.JFormattedTextField();
		peso1JFT = new javax.swing.JFormattedTextField();
		cptf2JFT = new javax.swing.JFormattedTextField();
		cptf1JFT = new javax.swing.JFormattedTextField();
		pronta2JFT = new javax.swing.JFormattedTextField();
		pronta1JFT = new javax.swing.JFormattedTextField();
		esgor2JFT = new javax.swing.JFormattedTextField();
		esgor1JFT = new javax.swing.JFormattedTextField();

		tatuagemHist3_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		tatuagemHist3_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel42.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel43.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel45.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		baiaJP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

		jLabel44.setText("Data");
		try {
			dataJFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		dataJFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		dataJFT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dataJFTActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout baiaJPLayout = new javax.swing.GroupLayout(baiaJP);
		baiaJPLayout.setHorizontalGroup(
			baiaJPLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(baiaJPLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabel44)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(dataJFT, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(289, Short.MAX_VALUE))
		);
		baiaJPLayout.setVerticalGroup(
			baiaJPLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(baiaJPLayout.createSequentialGroup()
					.addContainerGap()
					.addGroup(baiaJPLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel44)
						.addComponent(dataJFT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		baiaJP.setLayout(baiaJPLayout);

		registrosLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		registrosLabel.setForeground(new java.awt.Color(0, 153, 255));
		registrosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		registrosLabel.setText("Registros salvos com sucesso!!");

		jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel24.setText("Opções:");

		jLabel25.setText("<html>[9999] - Digite na tatuagem para <br/> começar uma nova data. </html>");

		jLabel50.setText("[ESC] - Voltar para tela anterior");

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel7Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel50)
								.addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel24))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel7Layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel24).addGap(18, 18, 18)
						.addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel50).addGap(54, 54, 54)));

		pnlBarriga.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel7.setText("Avaliação Barriga");

		jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel15.setText("CPTPF");

		try {
			cptf3JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		cptf3JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		cptf3JFT.setEnabled(false);

		jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel16.setText("PRONT");

		try {
			pronta3JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		pronta3JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		pronta3JFT.setEnabled(false);

		try {
			peso3JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		peso3JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		peso3JFT.setToolTipText("");
		peso3JFT.setEnabled(false);

		jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel28.setText("PESO");

		try {
			tatuagemJFT3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		tatuagemJFT3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		tatuagemJFT3.setEnabled(false);

		jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel29.setText("TATU");

		try {
			controleJFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		controleJFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		controleJFT.setEnabled(false);
		controleJFT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				controleJFTActionPerformed(evt);
			}
		});

		jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel35.setText("Controle");

		jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel17.setText("ESGOR");

		try {
			esgor3JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		esgor3JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		esgor3JFT.setEnabled(false);

		tatuagemHist3_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		tatuagemHist3_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		tatuagemHist2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		tatuagemHist2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		tatuagemHist1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		tatuagemHist1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pesoHist3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pesoHist3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pesoHist2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pesoHist2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		pesoHist1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		pesoHist1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		cptfHist3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		cptfHist3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		cptfHist2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		cptfHist2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		cptfHist1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		cptfHist1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		prontaHist3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		prontaHist3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		prontaHist2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		prontaHist2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		prontaHist1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		prontaHist1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		esgorHist3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		esgorHist3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		esgorHist2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		esgorHist2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		esgorHist1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		esgorHist1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		try {
			tatuagemJFT2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		tatuagemJFT2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		tatuagemJFT2.setEnabled(false);

		try {
			tatuagemJFT1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		tatuagemJFT1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		tatuagemJFT1.setEnabled(false);

		try {
			peso2JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		peso2JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		peso2JFT.setToolTipText("");
		peso2JFT.setEnabled(false);

		try {
			peso1JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		peso1JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		peso1JFT.setToolTipText("");
		peso1JFT.setEnabled(false);

		try {
			cptf2JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		cptf2JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		cptf2JFT.setEnabled(false);

		try {
			cptf1JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		cptf1JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		cptf1JFT.setEnabled(false);

		try {
			pronta2JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		pronta2JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		pronta2JFT.setEnabled(false);

		try {
			pronta1JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		pronta1JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		pronta1JFT.setEnabled(false);

		try {
			esgor2JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		esgor2JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		esgor2JFT.setEnabled(false);

		try {
			esgor1JFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		esgor1JFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		esgor1JFT.setEnabled(false);

		javax.swing.GroupLayout pnlBarrigaLayout = new javax.swing.GroupLayout(pnlBarriga);
		pnlBarrigaLayout.setHorizontalGroup(
			pnlBarrigaLayout.createParallelGroup(Alignment.LEADING)
				.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
				.addGroup(pnlBarrigaLayout.createSequentialGroup()
					.addContainerGap()
					.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.TRAILING, false)
						.addComponent(tatuagemJFT1)
						.addComponent(tatuagemHist1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(tatuagemHist2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(tatuagemHist3_1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel29, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
						.addComponent(tatuagemJFT3, Alignment.LEADING)
						.addComponent(tatuagemJFT2))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(pesoHist1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(pesoHist2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(pesoHist3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel28, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(peso1JFT)
						.addComponent(peso2JFT)
						.addComponent(peso3JFT, GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
					.addGap(6)
					.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING)
						.addGroup(pnlBarrigaLayout.createSequentialGroup()
							.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING)
								.addComponent(cptf2JFT, 51, 51, 51)
								.addComponent(cptf3JFT, 51, 51, 51)
								.addComponent(cptf1JFT, 51, 51, 51)
								.addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING)
								.addGroup(pnlBarrigaLayout.createSequentialGroup()
									.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING)
										.addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
										.addComponent(pronta3JFT, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
										.addComponent(pronta2JFT, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE))
									.addGap(6)
									.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
										.addGroup(pnlBarrigaLayout.createSequentialGroup()
											.addComponent(esgor2JFT, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(ComponentPlacement.RELATED)
											.addComponent(jLabel35, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGroup(pnlBarrigaLayout.createSequentialGroup()
											.addComponent(esgor3JFT, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(ComponentPlacement.RELATED)
											.addComponent(controleJFT, 79, 79, 79))))
								.addGroup(pnlBarrigaLayout.createSequentialGroup()
									.addComponent(pronta1JFT, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(esgor1JFT, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE))))
						.addGroup(pnlBarrigaLayout.createSequentialGroup()
							.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(cptfHist3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(cptfHist2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(cptfHist1, GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(prontaHist3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(prontaHist2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(prontaHist1, GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(esgorHist3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(esgorHist2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(esgorHist1, GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))))
					.addContainerGap(33, Short.MAX_VALUE))
		);
		pnlBarrigaLayout.setVerticalGroup(
			pnlBarrigaLayout.createParallelGroup(Alignment.TRAILING)
				.addGroup(pnlBarrigaLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabel7)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(tatuagemHist1, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
						.addComponent(pesoHist1, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
						.addComponent(cptfHist1, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
						.addComponent(prontaHist1, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
						.addComponent(esgorHist1, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(tatuagemHist2, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
						.addComponent(pesoHist2, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
						.addComponent(cptfHist2, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
						.addComponent(prontaHist2, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
						.addComponent(esgorHist2, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(esgorHist3, GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
						.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.LEADING, false)
							.addComponent(prontaHist3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(pesoHist3, GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
							.addComponent(tatuagemHist3_1, GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
							.addComponent(cptfHist3, GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel16)
						.addComponent(jLabel29)
						.addComponent(jLabel17)
						.addComponent(jLabel28)
						.addComponent(jLabel15))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(tatuagemJFT1, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(pronta1JFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(esgor1JFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(peso1JFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(cptf1JFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(tatuagemJFT2, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(pronta2JFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(esgor2JFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(peso2JFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(cptf2JFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel35))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(pnlBarrigaLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(tatuagemJFT3, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(pronta3JFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(peso3JFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(cptf3JFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(esgor3JFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(controleJFT, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(19, Short.MAX_VALUE))
		);
		pnlBarriga.setLayout(pnlBarrigaLayout);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(pnlBarriga, GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
								.addComponent(baiaJP, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(registrosLabel, GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)))
					.addContainerGap())
		);
		jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addComponent(baiaJP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(pnlBarriga, GroupLayout.PREFERRED_SIZE, 211, GroupLayout.PREFERRED_SIZE))
						.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addComponent(registrosLabel)
					.addGap(21))
		);
		jPanel2.setLayout(jPanel2Layout);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 636, GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 318, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(32, Short.MAX_VALUE))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 338, GroupLayout.PREFERRED_SIZE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void dataJFTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dataJFTActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_dataJFTActionPerformed

	private void controleJFTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_controleJFTActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_controleJFTActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ViewDigitarBarrigaST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ViewDigitarBarrigaST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ViewDigitarBarrigaST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ViewDigitarBarrigaST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ViewDigitarBarrigaST().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel baiaJP;
	private javax.swing.JFormattedTextField controleJFT;
	private javax.swing.JFormattedTextField cptf1JFT;
	private javax.swing.JFormattedTextField cptf2JFT;
	private javax.swing.JFormattedTextField cptf3JFT;
	private javax.swing.JLabel cptfHist1;
	private javax.swing.JLabel cptfHist2;
	private javax.swing.JLabel cptfHist3;
	private javax.swing.JFormattedTextField dataJFT;
	private javax.swing.JFormattedTextField esgor1JFT;
	private javax.swing.JFormattedTextField esgor2JFT;
	private javax.swing.JFormattedTextField esgor3JFT;
	private javax.swing.JLabel esgorHist1;
	private javax.swing.JLabel esgorHist2;
	private javax.swing.JLabel esgorHist3;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel tatuagemHist3;
	private JLabel tatuagemHist3_1;
	private javax.swing.JLabel jLabel35;
	private javax.swing.JLabel jLabel42;
	private javax.swing.JLabel jLabel43;
	private javax.swing.JLabel jLabel44;
	private javax.swing.JLabel jLabel45;
	private javax.swing.JLabel jLabel50;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JFormattedTextField peso1JFT;
	private javax.swing.JFormattedTextField peso2JFT;
	private javax.swing.JFormattedTextField peso3JFT;
	private javax.swing.JLabel pesoHist1;
	private javax.swing.JLabel pesoHist2;
	private javax.swing.JLabel pesoHist3;
	private javax.swing.JPanel pnlBarriga;
	private javax.swing.JFormattedTextField pronta1JFT;
	private javax.swing.JFormattedTextField pronta2JFT;
	private javax.swing.JFormattedTextField pronta3JFT;
	private javax.swing.JLabel prontaHist1;
	private javax.swing.JLabel prontaHist2;
	private javax.swing.JLabel prontaHist3;
	private javax.swing.JLabel registrosLabel;
	private javax.swing.JLabel tatuagemHist1;
	private javax.swing.JLabel tatuagemHist2;
	private javax.swing.JFormattedTextField tatuagemJFT3;
	private javax.swing.JFormattedTextField tatuagemJFT2;
	private javax.swing.JFormattedTextField tatuagemJFT1;
	// End of variables declaration//GEN-END:variables
	public javax.swing.JFormattedTextField getTatuagemJFT3() {
		return tatuagemJFT3;
	}

	public void setTatuagemJFT3(javax.swing.JFormattedTextField tatuagemJFT3) {
		this.tatuagemJFT3 = tatuagemJFT3;
	}

	public javax.swing.JPanel getBaiaJP() {
		return baiaJP;
	}

	public void setBaiaJP(javax.swing.JPanel baiaJP) {
		this.baiaJP = baiaJP;
	}

	public javax.swing.JFormattedTextField getControleJFT() {
		return controleJFT;
	}

	public void setControleJFT(javax.swing.JFormattedTextField controleJFT) {
		this.controleJFT = controleJFT;
	}

	public javax.swing.JFormattedTextField getCptf1JFT() {
		return cptf1JFT;
	}

	public void setCptf1JFT(javax.swing.JFormattedTextField cptf1jft) {
		cptf1JFT = cptf1jft;
	}

	public javax.swing.JFormattedTextField getCptf2JFT() {
		return cptf2JFT;
	}

	public void setCptf2JFT(javax.swing.JFormattedTextField cptf2jft) {
		cptf2JFT = cptf2jft;
	}

	public javax.swing.JFormattedTextField getCptf3JFT() {
		return cptf3JFT;
	}

	public void setCptf3JFT(javax.swing.JFormattedTextField cptf3jft) {
		cptf3JFT = cptf3jft;
	}

	public javax.swing.JLabel getCptfHist1() {
		return cptfHist1;
	}

	public void setCptfHist1(javax.swing.JLabel cptfHist1) {
		this.cptfHist1 = cptfHist1;
	}

	public javax.swing.JLabel getCptfHist2() {
		return cptfHist2;
	}

	public void setCptfHist2(javax.swing.JLabel cptfHist2) {
		this.cptfHist2 = cptfHist2;
	}

	public javax.swing.JLabel getCptfHist3() {
		return cptfHist3;
	}

	public void setCptfHist3(javax.swing.JLabel cptfHist3) {
		this.cptfHist3 = cptfHist3;
	}

	public javax.swing.JFormattedTextField getDataJFT() {
		return dataJFT;
	}

	public void setDataJFT(javax.swing.JFormattedTextField dataJFT) {
		this.dataJFT = dataJFT;
	}

	public javax.swing.JFormattedTextField getEsgor1JFT() {
		return esgor1JFT;
	}

	public void setEsgor1JFT(javax.swing.JFormattedTextField esgor1jft) {
		esgor1JFT = esgor1jft;
	}

	public javax.swing.JFormattedTextField getEsgor2JFT() {
		return esgor2JFT;
	}

	public void setEsgor2JFT(javax.swing.JFormattedTextField esgor2jft) {
		esgor2JFT = esgor2jft;
	}

	public javax.swing.JFormattedTextField getEsgor3JFT() {
		return esgor3JFT;
	}

	public void setEsgor3JFT(javax.swing.JFormattedTextField esgor3jft) {
		esgor3JFT = esgor3jft;
	}

	public javax.swing.JLabel getEsgorHist1() {
		return esgorHist1;
	}

	public void setEsgorHist1(javax.swing.JLabel esgorHist1) {
		this.esgorHist1 = esgorHist1;
	}

	public javax.swing.JLabel getEsgorHist2() {
		return esgorHist2;
	}

	public void setEsgorHist2(javax.swing.JLabel esgorHist2) {
		this.esgorHist2 = esgorHist2;
	}

	public javax.swing.JLabel getEsgorHist3() {
		return esgorHist3;
	}

	public void setEsgorHist3(javax.swing.JLabel esgorHist3) {
		this.esgorHist3 = esgorHist3;
	}

	public javax.swing.JLabel getjLabel15() {
		return jLabel15;
	}

	public void setjLabel15(javax.swing.JLabel jLabel15) {
		this.jLabel15 = jLabel15;
	}

	public javax.swing.JLabel getjLabel16() {
		return jLabel16;
	}

	public void setjLabel16(javax.swing.JLabel jLabel16) {
		this.jLabel16 = jLabel16;
	}

	public javax.swing.JLabel getjLabel17() {
		return jLabel17;
	}

	public void setjLabel17(javax.swing.JLabel jLabel17) {
		this.jLabel17 = jLabel17;
	}

	public javax.swing.JLabel getjLabel24() {
		return jLabel24;
	}

	public void setjLabel24(javax.swing.JLabel jLabel24) {
		this.jLabel24 = jLabel24;
	}

	public javax.swing.JLabel getjLabel25() {
		return jLabel25;
	}

	public void setjLabel25(javax.swing.JLabel jLabel25) {
		this.jLabel25 = jLabel25;
	}

	public javax.swing.JLabel getjLabel28() {
		return jLabel28;
	}

	public void setjLabel28(javax.swing.JLabel jLabel28) {
		this.jLabel28 = jLabel28;
	}

	public javax.swing.JLabel getjLabel29() {
		return jLabel29;
	}

	public void setjLabel29(javax.swing.JLabel jLabel29) {
		this.jLabel29 = jLabel29;
	}

	public javax.swing.JLabel getTatuagemHist3() {
		return tatuagemHist3;
	}

	public void setTatuagemHist3(javax.swing.JLabel tatuagemHist3) {
		this.tatuagemHist3 = tatuagemHist3;
	}

	public JLabel getTatuagemHist3_1() {
		return tatuagemHist3_1;
	}

	public void setTatuagemHist3_1(JLabel tatuagemHist3_1) {
		this.tatuagemHist3_1 = tatuagemHist3_1;
	}

	public javax.swing.JLabel getjLabel35() {
		return jLabel35;
	}

	public void setjLabel35(javax.swing.JLabel jLabel35) {
		this.jLabel35 = jLabel35;
	}

	public javax.swing.JLabel getjLabel42() {
		return jLabel42;
	}

	public void setjLabel42(javax.swing.JLabel jLabel42) {
		this.jLabel42 = jLabel42;
	}

	public javax.swing.JLabel getjLabel43() {
		return jLabel43;
	}

	public void setjLabel43(javax.swing.JLabel jLabel43) {
		this.jLabel43 = jLabel43;
	}

	public javax.swing.JLabel getjLabel44() {
		return jLabel44;
	}

	public void setjLabel44(javax.swing.JLabel jLabel44) {
		this.jLabel44 = jLabel44;
	}

	public javax.swing.JLabel getjLabel45() {
		return jLabel45;
	}

	public void setjLabel45(javax.swing.JLabel jLabel45) {
		this.jLabel45 = jLabel45;
	}

	public javax.swing.JLabel getjLabel50() {
		return jLabel50;
	}

	public void setjLabel50(javax.swing.JLabel jLabel50) {
		this.jLabel50 = jLabel50;
	}

	public javax.swing.JLabel getjLabel7() {
		return jLabel7;
	}

	public void setjLabel7(javax.swing.JLabel jLabel7) {
		this.jLabel7 = jLabel7;
	}

	public javax.swing.JPanel getjPanel1() {
		return jPanel1;
	}

	public void setjPanel1(javax.swing.JPanel jPanel1) {
		this.jPanel1 = jPanel1;
	}

	public javax.swing.JPanel getjPanel2() {
		return jPanel2;
	}

	public void setjPanel2(javax.swing.JPanel jPanel2) {
		this.jPanel2 = jPanel2;
	}

	public javax.swing.JPanel getjPanel7() {
		return jPanel7;
	}

	public void setjPanel7(javax.swing.JPanel jPanel7) {
		this.jPanel7 = jPanel7;
	}

	public javax.swing.JFormattedTextField getPeso1JFT() {
		return peso1JFT;
	}

	public void setPeso1JFT(javax.swing.JFormattedTextField peso1jft) {
		peso1JFT = peso1jft;
	}

	public javax.swing.JFormattedTextField getPeso2JFT() {
		return peso2JFT;
	}

	public void setPeso2JFT(javax.swing.JFormattedTextField peso2jft) {
		peso2JFT = peso2jft;
	}

	public javax.swing.JFormattedTextField getPeso3JFT() {
		return peso3JFT;
	}

	public void setPeso3JFT(javax.swing.JFormattedTextField peso3jft) {
		peso3JFT = peso3jft;
	}

	public javax.swing.JLabel getPesoHist1() {
		return pesoHist1;
	}

	public void setPesoHist1(javax.swing.JLabel pesoHist1) {
		this.pesoHist1 = pesoHist1;
	}

	public javax.swing.JLabel getPesoHist2() {
		return pesoHist2;
	}

	public void setPesoHist2(javax.swing.JLabel pesoHist2) {
		this.pesoHist2 = pesoHist2;
	}

	public javax.swing.JLabel getPesoHist3() {
		return pesoHist3;
	}

	public void setPesoHist3(javax.swing.JLabel pesoHist3) {
		this.pesoHist3 = pesoHist3;
	}

	public javax.swing.JPanel getPnlBarriga() {
		return pnlBarriga;
	}

	public void setPnlBarriga(javax.swing.JPanel pnlBarriga) {
		this.pnlBarriga = pnlBarriga;
	}

	public javax.swing.JFormattedTextField getPronta1JFT() {
		return pronta1JFT;
	}

	public void setPronta1JFT(javax.swing.JFormattedTextField pronta1jft) {
		pronta1JFT = pronta1jft;
	}

	public javax.swing.JFormattedTextField getPronta2JFT() {
		return pronta2JFT;
	}

	public void setPronta2JFT(javax.swing.JFormattedTextField pronta2jft) {
		pronta2JFT = pronta2jft;
	}

	public javax.swing.JFormattedTextField getPronta3JFT() {
		return pronta3JFT;
	}

	public void setPronta3JFT(javax.swing.JFormattedTextField pronta3jft) {
		pronta3JFT = pronta3jft;
	}

	public javax.swing.JLabel getProntaHist1() {
		return prontaHist1;
	}

	public void setProntaHist1(javax.swing.JLabel prontaHist1) {
		this.prontaHist1 = prontaHist1;
	}

	public javax.swing.JLabel getProntaHist2() {
		return prontaHist2;
	}

	public void setProntaHist2(javax.swing.JLabel prontaHist2) {
		this.prontaHist2 = prontaHist2;
	}

	public javax.swing.JLabel getProntaHist3() {
		return prontaHist3;
	}

	public void setProntaHist3(javax.swing.JLabel prontaHist3) {
		this.prontaHist3 = prontaHist3;
	}

	public javax.swing.JLabel getRegistrosLabel() {
		return registrosLabel;
	}

	public void setRegistrosLabel(javax.swing.JLabel registrosLabel) {
		this.registrosLabel = registrosLabel;
	}

	public javax.swing.JLabel getTatuagemHist1() {
		return tatuagemHist1;
	}

	public void setTatuagemHist1(javax.swing.JLabel tatuagemHist1) {
		this.tatuagemHist1 = tatuagemHist1;
	}

	public javax.swing.JLabel getTatuagemHist2() {
		return tatuagemHist2;
	}

	public void setTatuagemHist2(javax.swing.JLabel tatuagemHist2) {
		this.tatuagemHist2 = tatuagemHist2;
	}

	public javax.swing.JFormattedTextField getTatuagemJFT2() {
		return tatuagemJFT2;
	}

	public void setTatuagemJFT2(javax.swing.JFormattedTextField tatuagemJFT2) {
		this.tatuagemJFT2 = tatuagemJFT2;
	}

	public javax.swing.JFormattedTextField getTatuagemJFT1() {
		return tatuagemJFT1;
	}

	public void setTatuagemJFT1(javax.swing.JFormattedTextField tatuagemJFT1) {
		this.tatuagemJFT1 = tatuagemJFT1;
	}

}
